# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build jorne nice_nano_v2'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["jorne_left","jorne_right"]'
      branches: '["zmkfirmware/zmk/v0.3-branch"]'
      alphas: '["QWERTY"]'
      kconfig: '["CONFIG_ZMK_POINTING=y"]'
